# Generated by Django 3.1.2 on 2020-10-25 11:45

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='Gallery', max_length=100)),
                ('img', models.ImageField(upload_to='Gallery')),
            ],
        ),
        migrations.CreateModel(
            name='Celebrity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=30)),
                ('dateofbirth', models.DateTimeField()),
                ('birthplace', models.CharField(max_length=100)),
                ('profession', models.CharField(max_length=100)),
                ('maritalstatus', models.CharField(max_length=50)),
                ('nationality', models.CharField(max_length=20)),
                ('todaysDate', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('author', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('celebrity', 'Celebrity')], default='celebrity', max_length=10)),
                ('heading', models.CharField(max_length=250)),
                ('bio_and_family', models.TextField(blank=True)),
                ('career', models.TextField(blank=True)),
                ('hobbies', models.TextField(blank=True)),
                ('relationship', models.TextField(blank=True)),
                ('networth', models.TextField(blank=True)),
                ('img1', models.ImageField(upload_to='Celebrity')),
                ('img2', models.ImageField(upload_to='Celebrity')),
                ('img3', models.ImageField(upload_to='Celebrity')),
                ('postedby', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='celebrityPost', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
