# Generated by Django 3.1.2 on 2020-10-26 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0003_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title4',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
