# Generated by Django 3.1.2 on 2020-10-28 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0006_article_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='QuickFact1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact1Ans',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact2Ans',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact3',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact3Ans',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact4',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact4Ans',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact5',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact5Ans',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact6',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact6Ans',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact7',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='article',
            name='QuickFact7Ans',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
