# Generated by Django 3.1.2 on 2020-10-28 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0007_auto_20201028_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='QuickFact4',
        ),
        migrations.RemoveField(
            model_name='article',
            name='QuickFact4Ans',
        ),
        migrations.RemoveField(
            model_name='article',
            name='QuickFact5',
        ),
        migrations.RemoveField(
            model_name='article',
            name='QuickFact5Ans',
        ),
        migrations.RemoveField(
            model_name='article',
            name='QuickFact6',
        ),
        migrations.RemoveField(
            model_name='article',
            name='QuickFact6Ans',
        ),
        migrations.RemoveField(
            model_name='article',
            name='QuickFact7',
        ),
        migrations.RemoveField(
            model_name='article',
            name='QuickFact7Ans',
        ),
    ]
