# Generated by Django 3.1.2 on 2020-10-28 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0008_auto_20201028_1605'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='title1',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title1_Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title2',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title2_Description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='article',
            name='title3',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='article',
            name='title3_Description',
            field=models.TextField(),
        ),
    ]
