# Generated by Django 3.1.2 on 2020-10-29 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Article', '0009_auto_20201028_1613'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='title5',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='article',
            name='title5_Description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='QuickFact1',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='QuickFact1Ans',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='QuickFact2',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='QuickFact2Ans',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='article',
            name='QuickFact3',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='article',
            name='QuickFact3Ans',
            field=models.CharField(max_length=50),
        ),
    ]
